# Generated by Django 4.0.5 on 2022-09-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularplace',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='fee',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='popularplace',
            name='place_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
