# Generated by Django 4.0.5 on 2022-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_popularplace_duration_popularplace_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('flying_from', models.CharField(max_length=50)),
                ('flying_to', models.CharField(max_length=50)),
                ('departing_date', models.DateField()),
                ('return_date', models.DateField()),
                ('adults', models.CharField(max_length=5)),
                ('childrens', models.CharField(max_length=5)),
                ('travel_class', models.CharField(max_length=10)),
            ],
        ),
    ]
